version: "3.8"
services:
  postgres:
    image: ivanipani1/relational-db:postgres
    # ports:
    #   - "5432:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 5s
      retries: 5

  dev: &dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/workarea
    environment:
      - KC_DB_URL=jdbc:postgresql://postgres:5432/postgres
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=my_postgres_password
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=change_me
    command: start-dev
    depends_on:
      postgres:
        condition: service_healthy

  deploy:
    build:
      context: .
      dockerfile: deploy.Dockerfile
    ports:
      - "8443:8443"
    environment:
      - KC_DB_URL=jdbc:postgresql://postgres:5432/postgres
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=my_postgres_password
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=change_me
    command: start

